export const API_CONSTANTS = {
  POSTS_PER_PAGE: 10,
  INFINITE_SCROLL_THRESHOLD: 100,
  SCROLL_INIT_DELAY: 100,
} as const;

export const UI_CONSTANTS = {
  NEWS_CARD_BODY_MAX_LINES: 3,
  LOADING_SPINNER_MIN_HEIGHT: 200,
  LOADING_SPINNER_PADDING: 40,
  NEWS_CARD_SPACING: 16,
  HEADER_HEIGHT: 64,
  CONTENT_PADDING: 24,
  MAX_CONTENT_WIDTH: 800,
} as const;

export const HTTP_STATUS = {
  OK: 200,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
} as const;
